#! /bin/bash

#   nelr              = int(sys.argv[1])
#   visu              = int(sys.argv[2])
#   nqperdim          = int(sys.argv[3])
#   mapping           = int(sys.argv[4])
#   xi                = int(sys.argv[5])
#   blob_eta          = float(sys.argv[6])
#   blob_rho          = float(sys.argv[7])
#   blob_z            = float(sys.argv[8])
#   blob_R            = float(sys.argv[9])
#   blob_theta        = float(sys.argv[10])
#   blob_R1           = float(sys.argv[11])
#   blob_R2           = float(sys.argv[12])
#   crust_rho         = float(sys.argv[13])
#   crust_eta         = float(sys.argv[14])
#   crust_depth       = float(sys.argv[15])
#   lithosphere_rho   = float(sys.argv[16])
#   lithosphere_eta   = float(sys.argv[17])
#   lithosphere_depth = float(sys.argv[18])
#   uppermantle_rho   = float(sys.argv[19])
#   uppermantle_eta   = float(sys.argv[20])
#   uppermantle_depth = float(sys.argv[21])
#   lowermantle_rho   = float(sys.argv[22])
#   lowermantle_eta   = float(sys.argv[23])

nqperdim=3
mapping=2
xi=6

for l in 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 68 72 76 80 84 88 92 96 100 104 108 112 116 120 128 144 160 192 224 256 ; do

    echo nelr= $l - nqperdim= $nqperdim - mapping= $mapping - xi= $xi

    python3 flaps.py $l 1 $nqperdim $mapping $xi 23 3960 4900000 400000 0 0 0 4000 21 0 4000 21 0 4000 21 0 4000 21 > opla_${l}_${xi}

    mv vel_R2_0.ascii vel_R2.ascii_${l}_${xi}
    mv qqq_R2_0.ascii qqq_R2.ascii_${l}_${xi}
    mv err_R2_0.ascii err_R2.ascii_${l}_${xi}
    mv d_t_R1_0.ascii d_t_R1.ascii_${l}_${xi}
    mv d_t_R2_0.ascii d_t_R2.ascii_${l}_${xi}
    mv sr2_R2_0.ascii sr2_R2.ascii_${l}_${xi}
    mv solution_0.vtu solution_${l}_${xi}.vtu

    grep 4DEARTH opla_${l}_${xi} | grep v_r >> v_r_4DEARTH.ascii
    grep 4DEARTH opla_${l}_${xi} | grep v_t >> v_t_4DEARTH.ascii
    grep 4DEARTH opla_${l}_${xi} | grep mass_blob >> mass_blob_4DEARTH.ascii
    grep total opla_${l}_${xi} | grep mass >> total_mass_4DEARTH.ascii
    grep vrms opla_${l}_${xi} >> vrms_4DEARTH.ascii

done

