#! /bin/bash
#   nelr        = int(sys.argv[1])
#   visu        = int(sys.argv[2])
#   nqperdim    = int(sys.argv[3])
#   mapping     = int(sys.argv[4])
#   xi          = int(sys.argv[5])
#   etablob     = float(sys.argv[6])
#   rhoblob     = float(sys.argv[7])
#   zblob       = float(sys.argv[8])
#   Rblob       = float(sys.argv[9])
#   etalith     = float(sys.argv[10])

nqperdim=3
mapping=2
xi=6

for l in 32 48 64 80 96 128; do

    echo nelr= $l - nqperdim= $nqperdim - mapping= $mapping - xi= $xi

    python3 flaps.py $l 1 $nqperdim $mapping $xi 22 3950 4900000  400000 1 > opla_${l}_${xi}

    mv vel_R2_0.ascii vel_R2.ascii_${l}_${xi}
    mv qqq_R2_0.ascii qqq_R2.ascii_${l}_${xi}
    mv err_R2_0.ascii err_R2.ascii_${l}_${xi}
    mv d_t_R2_0.ascii d_t_R2.ascii_${l}_${xi}
    mv sr2_R2_0.ascii sr2_R2.ascii_${l}_${xi}
    mv solution_0.vtu solution_${l}_${xi}.vtu

    grep 4DEARTH opla_${l}_${xi} | grep v_r >> v_r_4DEARTH.ascii
    grep 4DEARTH opla_${l}_${xi} | grep v_t >> v_t_4DEARTH.ascii
    grep vrms opla_${l}_${xi} >> vrms_4DEARTH.ascii

done


