#! /bin/bash
#   exp         = int(sys.argv[1])
#   nelr        = int(sys.argv[2])
#   visu        = int(sys.argv[3])
#   nqperdim    = int(sys.argv[4])
#   mapping     = int(sys.argv[5])
#   xi          = int(sys.argv[6])
#   etablobstar = float(sys.argv[7])
#   rhoblobstar = float(sys.argv[8])
#   yblob       = float(sys.argv[9])
#   Rblob       = float(sys.argv[10])
#   etalithstar = float(sys.argv[11])



xi=6
nqperdim=3
mapping=2

for l in 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 40 44 48 52 56 60 64 68 72 76 80 88 96 112 128 144 160 192 256; do

    echo nelr= $l - nqperdim= $nqperdim - mapping= $mapping - xi= $xi

    python3 flaps.py 0 $l 1 $nqperdim $mapping $xi 1 1 0 0 1 > opla

    grep sanity opla >> sanity.ascii 
    grep solving opla >> solving.ascii 
    grep build opla | grep FE >> build.ascii 

done
