#! /bin/bash
#   exp         = int(sys.argv[1])
#   nelr        = int(sys.argv[2])
#   visu        = int(sys.argv[3])
#   nqperdim    = int(sys.argv[4])
#   mapping     = int(sys.argv[5])
#   xi          = int(sys.argv[6])
#   etablobstar = float(sys.argv[7])
#   rhoblobstar = float(sys.argv[8])
#   zblob       = float(sys.argv[9])
#   Rblob       = float(sys.argv[10])
#   etalithstar = float(sys.argv[11])

nqperdim=3
mapping=2
xi=6

for l in 32 48 64 96 128 192 256; do

    echo nelr= $l - nqperdim= $nqperdim - mapping= $mapping - xi= $xi

    python3 flaps.py 2 $l 1 $nqperdim $mapping $xi 1 0.99 4900000  400000 1 > opla_${l}_${xi}

    mv vel_R2_0.ascii vel_R2.ascii_${l}_${xi}
    mv qqq_R2_0.ascii qqq_R2.ascii_${l}_${xi}
    mv err_R2_0.ascii err_R2.ascii_${l}_${xi}
    mv d_t_R2_0.ascii d_t_R2.ascii_${l}_${xi}
    mv sr2_R2_0.ascii sr2_R2.ascii_${l}_${xi}
    mv solution_0.vtu solution_${l}_${xi}.vtu

    grep EARTH4D opla_${l}_${xi} | grep v_r >> v_r_EARTH4D.ascii
    grep EARTH4D opla_${l}_${xi} | grep v_t >> v_t_EARTH4D.ascii
    grep EARTH4D opla_${l}_${xi} | grep v_rms >> v_rms_EARTH4D.ascii

done


